<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/** @CONFIG FOR PASSWORD ENCRYPTION SALT */
$config['PASSWORD_ENCRYPTION_SALT_BEFORE'] = 'JUST_CODEIGNITER';
$config['PASSWORD_ENCRYPTION_SALT_AFTER'] = 'BY_BOONYAPHAT';

/** @CONFIG FOR PASSWORD ENCRYPTION AES */
$config['ENCRYPTION_DEFAULT_KEY'] = 'JUST_CODEIGNITER_KEY';
$config['ENCRYPTION_DEFAULT_IV'] = 'JUST_CODEIGNITER_IV';
$config['ENCRYPTION_ENABLE'] = 'ENABLED';
